### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by Periscope-NZ** [MatthiasWinkelmann/firstname-database#1]
What is the character encoding format of the file firstnames.csv? When viewing using UTF-8 I see a lot of garbled characters for some names. I suggest this be checked and updated in the documentation if possible

![composite_encode](https://user-images.githubusercontent.com/43570139/46006934-cee9d780-c10c-11e8-8f65-5297dd619cb8.png)

**Comment by KarlAmort** [comment]
Sorry for the slight delay! I've finally been bored enough (and scared of disappointing Saša Stanišić) that I got around to working on this.

The data here was initially collected in times before <strikeout>writing</strikeout> Unicode, and I believe it used some system with line-level specific encoding to represent the names. It's probably explained perfectly well in the first three lines of the README, but I felt more like writing than reading and made an algorithm make some guesses which changed some 800 names.

A further two hundred seemed to mix up encodings even between letters and I manually chose the most pleasant symbiosis by hand. This sound more haphjardous than it really is and these updates should drastically reduce the risk of international incidents arising from this data. 

A select few creative neologisms might yet emerge. Keep an eye out for children with question marks and/or squares in a few years.

Always open to pull requests, obviously. Someone more fluent especially in the languages of the Balkans might be helpful. 

Updates to the data for more recent years might also start to make sense.
